### ISSUE TITLE
[BUG] Image orientation change upon upload  due to transpose

### ISSUE THREAD

**Issue by BlanchardMR** [TheJacksonLaboratory/ezomero#54] opened 2022-06-12 13:25 UTC
**Describe the bug**
Line 183 of _posts.py transposes the image array possibly unnecessarily which causes user to transpose their image before uploading to Omero in order to maintain proper orientation. This may be intended behavior.
 ```
 def plane_gen(image, image_sizez, image_sizec, image_sizet):
        for z in range(image_sizez):
            for c in range(image_sizec):
                for t in range(image_sizet):
                    yield image[:, :, z, c, t].T 
```
The .T should be removed unless there is some other intended behavior.

**To Reproduce**
This behavior should apply to all images uploaded unless XY is of size 1,1. 

**Expected behavior**
The image uploaded to Omero should be of the same orientation as the image the user uploaded.

**Screenshots**
Image with transpose removed and not removed. And then overview with tile shown. ROI is Row: 0 Col:1
![notTransposed](https://user-images.githubusercontent.com/44418166/173234858-4835d4eb-5e88-4066-ac3f-f20366ae3950.JPG)
![withTranspose](https://user-images.githubusercontent.com/44418166/173234859-5e3fbf72-5068-4c06-9917-ed37561e594b.JPG)
![overview_context](https://user-images.githubusercontent.com/44418166/173235171-330fc1d7-032f-4dbc-a493-196f5beaf1e5.JPG)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Python version [3.9.2]
 - ezomero version [1.0.1]

**Additional context**

**Comment by mellertd** [comment] 2022-06-13 18:34
This was fine as originally released, not sure where the problem is. It's possible something changed with addition of `dim_order`. Is the confusion coming from the fact that OMEROs "natural" ordering is xyzct whereas anything numpy is yx ordered (hence the `.T`)?

**Comment by BlanchardMR** [comment] 2022-06-14 02:48
Yeah I think the confusion is primarily that when you call down a tile and probably a plane from Omero the np.array (I did confirm it is a np.array) is in the xy orientation so that if you do-something and then send it back to omero using ezomero.post_image the image will be transposed. I just assumed that the way the array was downloaded should be the same as uploaded. My guess is you guys interface with more yx orderings by the sound of it so maybe best to just keep it this way. It just seemed really weird at the time and caused some hair pulling assuming I had done the rotation somewhere.

**Comment by erickmartins** [comment] 2022-06-14 13:14
as a final sanity test, I did
```
>>> _, pix = ezomero.get_image(conn, 51, dim_order="xyzct")
>>> ezomero.post_image(conn, pix, "test", dim_order="xyzct")
```
and indeed the new image looks exactly like the original (ID=51). I think it's all behaving as intended. Ordering dimensions is always a pain!

**Comment by mellertd** [comment] 2022-06-15 12:03
Closing, since everything is working as intended

**Closed by mellertd** 2022-06-15 12:03 UTC
